"use client";

import type { LucideIcon } from "lucide-react";
import {
  AlertTriangle,
  Archive,
  ArrowDown,
  ArrowLeftRight,
  ArrowUp,
  Banknote,
  BarChart3,
  Ban,
  BookOpen,
  Briefcase,
  CalendarDays,
  CalendarRange,
  Check,
  CheckCircle2,
  ClipboardList,
  Clock3,
  CreditCard,
  Crown,
  DollarSign,
  Download,
  FileText,
  FolderOpen,
  Gift,
  GraduationCap,
  Hash,
  HandCoins,
  Home,
  Info,
  Link2,
  LogOut,
  Landmark,
  Menu,
  Moon,
  NotebookPen,
  Pencil,
  Pin,
  Play,
  Plus,
  Power,
  Printer,
  RefreshCw,
  ReceiptText,
  RotateCcw,
  Save,
  Scissors,
  Search,
  Settings,
  Sun,
  Sunrise,
  Tag,
  Trash2,
  TrendingUp,
  University,
  Upload,
  User,
  UserCheck,
  UserRoundCog,
  UserX,
  Users,
  Wallet,
  X,
  XCircle,
  Phone,
} from "lucide-react";

const iconMap: Record<string, LucideIcon> = {
  "📊": BarChart3,
  "👥": Users,
  "💳": CreditCard,
  "💰": Wallet,
  "💵": Banknote,
  "📈": TrendingUp,
  "📚": BookOpen,
  "🗓️": CalendarDays,
  "📅": CalendarDays,
  "👑": Crown,
  "🖨️": Printer,
  "📦": ArrowLeftRight,
  "⏸️": Power,
  "✏️": Pencil,
  "🗑️": Trash2,
  "↩️": RotateCcw,
  "✅": CheckCircle2,
  "✓": Check,
  "❌": XCircle,
  "✕": X,
  "⚠️": AlertTriangle,
  "⚠": AlertTriangle,
  "💸": HandCoins,
  "🏫": University,
  "🎓": GraduationCap,
  "🧾": ReceiptText,
  "📌": Pin,
  "📂": FolderOpen,
  "📆": CalendarRange,
  "💼": Briefcase,
  "💲": DollarSign,
  "➕": Plus,
  "👤": User,
  "🏦": Landmark,
  "📄": FileText,
  "🏷️": Tag,
  "🎁": Gift,
  "🔍": Search,
  "🔢": Hash,
  "📝": NotebookPen,
  "📞": Phone,
  "🚫": Ban,
  "⛔": Ban,
  "🚪": LogOut,
  "🔄": RefreshCw,
  "▶": Play,
  "☰": Menu,
  "🌅": Sunrise,
  "🌞": Sun,
  "🌙": Moon,
  "☀️": Sun,
  "💾": Save,
  "✂️": Scissors,
  "🔗": Link2,
  "⬆️": ArrowUp,
  "▼": ArrowDown,
  "▲": ArrowUp,
  "ℹ": Info,
  "📥": Download,
  "⬇️": Download,
  "📤": Upload,
  "⏰": Clock3,
  "📋": ClipboardList,
  "🗄️": Archive,
  "⚙️": Settings,
  "🏠": Home,
  "👨‍🏫": UserRoundCog,
  "👔": Briefcase,
  "✗": UserX,
  "$": DollarSign,
  "👁": UserCheck,
};

export function AppIcon({
  token,
  size = 16,
  strokeWidth = 2,
  className,
}: {
  token: string;
  size?: number;
  strokeWidth?: number;
  className?: string;
}) {
  const Icon = iconMap[token] || CircleFallback;
  return <Icon size={size} strokeWidth={strokeWidth} className={className} aria-hidden="true" />;
}

function CircleFallback({
  className,
  size = 16,
}: {
  className?: string;
  size?: number;
}) {
  return <div className={className} style={{ width: size, height: size, borderRadius: "999px", background: "currentColor", opacity: 0.25 }} />;
}
