export interface ThemePreset {
  id: string;
  name: string;
  nameAr: string;
  primaryColor: string;
  secondaryColor: string;
  accentColor: string;
  textColor: string;
  sidebarColor: string;
  topbarColor: string;
  fontFamily: string;
  borderRadius: "sm" | "md" | "lg" | "xl";
  darkModeEnabled: boolean;
  preview: string;
}

export const APP_THEME_PRESETS: ThemePreset[] = [
  {
    id: "ocean-blue",
    name: "Ocean Blue",
    nameAr: "أزرق المحيط",
    primaryColor: "#1e6cce",
    secondaryColor: "#64b5f6",
    accentColor: "#0d47a1",
    textColor: "#1a2332",
    sidebarColor: "#e8f1fb",
    topbarColor: "#1e6cce",
    fontFamily: "Cairo",
    borderRadius: "lg",
    darkModeEnabled: false,
    preview: "linear-gradient(135deg, #1e6cce, #64b5f6)",
  },
  {
    id: "emerald-garden",
    name: "Emerald Garden",
    nameAr: "حديقة الزمرد",
    primaryColor: "#059669",
    secondaryColor: "#6ee7b7",
    accentColor: "#047857",
    textColor: "#1a2e26",
    sidebarColor: "#ecfdf5",
    topbarColor: "#059669",
    fontFamily: "Cairo",
    borderRadius: "lg",
    darkModeEnabled: false,
    preview: "linear-gradient(135deg, #059669, #6ee7b7)",
  },
  {
    id: "royal-purple",
    name: "Royal Purple",
    nameAr: "بنفسجي ملكي",
    primaryColor: "#7c3aed",
    secondaryColor: "#c4b5fd",
    accentColor: "#6d28d9",
    textColor: "#1e1a2e",
    sidebarColor: "#f5f3ff",
    topbarColor: "#7c3aed",
    fontFamily: "Cairo",
    borderRadius: "xl",
    darkModeEnabled: false,
    preview: "linear-gradient(135deg, #7c3aed, #c4b5fd)",
  },
  {
    id: "sunset-warm",
    name: "Sunset Warm",
    nameAr: "غروب دافئ",
    primaryColor: "#ea580c",
    secondaryColor: "#fdba74",
    accentColor: "#c2410c",
    textColor: "#2a1a0e",
    sidebarColor: "#fff7ed",
    topbarColor: "#ea580c",
    fontFamily: "Cairo",
    borderRadius: "md",
    darkModeEnabled: false,
    preview: "linear-gradient(135deg, #ea580c, #fdba74)",
  },
  {
    id: "dark-professional",
    name: "Dark Professional",
    nameAr: "داكن احترافي",
    primaryColor: "#6366f1",
    secondaryColor: "#818cf8",
    accentColor: "#4f46e5",
    textColor: "#e2e8f0",
    sidebarColor: "#1e1b2e",
    topbarColor: "#0f0d1a",
    fontFamily: "Cairo",
    borderRadius: "lg",
    darkModeEnabled: true,
    preview: "linear-gradient(135deg, #1e1b2e, #6366f1)",
  },
  {
    id: "rose-elegant",
    name: "Rose Elegant",
    nameAr: "وردي أنيق",
    primaryColor: "#e11d48",
    secondaryColor: "#fda4af",
    accentColor: "#be123c",
    textColor: "#2a1219",
    sidebarColor: "#fff1f2",
    topbarColor: "#e11d48",
    fontFamily: "Cairo",
    borderRadius: "xl",
    darkModeEnabled: false,
    preview: "linear-gradient(135deg, #e11d48, #fda4af)",
  },
  {
    id: "teal-modern",
    name: "Teal Modern",
    nameAr: "أزرق مخضر عصري",
    primaryColor: "#0d9488",
    secondaryColor: "#5eead4",
    accentColor: "#0f766e",
    textColor: "#1a2c2a",
    sidebarColor: "#f0fdfa",
    topbarColor: "#0d9488",
    fontFamily: "Cairo",
    borderRadius: "md",
    darkModeEnabled: false,
    preview: "linear-gradient(135deg, #0d9488, #5eead4)",
  },
  {
    id: "golden-classic",
    name: "Golden Classic",
    nameAr: "ذهبي كلاسيكي",
    primaryColor: "#b45309",
    secondaryColor: "#fcd34d",
    accentColor: "#92400e",
    textColor: "#2a1f0a",
    sidebarColor: "#fffbeb",
    topbarColor: "#b45309",
    fontFamily: "Cairo",
    borderRadius: "md",
    darkModeEnabled: false,
    preview: "linear-gradient(135deg, #b45309, #fcd34d)",
  },
  {
    id: "midnight-dark",
    name: "Midnight Dark",
    nameAr: "منتصف الليل",
    primaryColor: "#3b82f6",
    secondaryColor: "#60a5fa",
    accentColor: "#2563eb",
    textColor: "#e2e8f0",
    sidebarColor: "#0f172a",
    topbarColor: "#020617",
    fontFamily: "Cairo",
    borderRadius: "lg",
    darkModeEnabled: true,
    preview: "linear-gradient(135deg, #0f172a, #3b82f6)",
  },
  {
    id: "slate-minimal",
    name: "Slate Minimal",
    nameAr: "رمادي بسيط",
    primaryColor: "#475569",
    secondaryColor: "#94a3b8",
    accentColor: "#334155",
    textColor: "#1e293b",
    sidebarColor: "#f1f5f9",
    topbarColor: "#475569",
    fontFamily: "Cairo",
    borderRadius: "sm",
    darkModeEnabled: false,
    preview: "linear-gradient(135deg, #475569, #94a3b8)",
  },
];

export function getAppThemePreset(presetId: string): ThemePreset | undefined {
  return APP_THEME_PRESETS.find((p) => p.id === presetId);
}
