/**
 * A5 styled payment receipt template with school decorations.
 * Renders a self-contained HTML document for window.print() via printHtmlDocument().
 */

export type ReceiptConfig = {
  decoration_top_left?: string | null;
  decoration_top_right?: string | null;
  decoration_bottom_left?: string | null;
  decoration_bottom_right?: string | null;
  background_pattern_url?: string | null;
  emblem_url?: string | null;
  thank_you_text?: string | null;
  footer_note?: string | null;
  primary_color?: string | null;
  accent_color?: string | null;
};

export type ReceiptInput = {
  locale: "ar" | "en";
  schoolName: string;
  branchName?: string | null;
  schoolLogoUrl?: string | null;
  receiptNumber: string;
  studentName: string;
  className: string;
  paymentMethod: string;
  paymentDate: string;
  totalFee: number;
  discount: number;
  paidNow: number;
  remaining: number;
  notes?: string | null;
  config?: ReceiptConfig | null;
  autoPrint?: boolean;
};

function escapeHtml(input: string | null | undefined): string {
  return String(input ?? "")
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");
}

function fmtMoney(value: number, locale: "ar" | "en"): string {
  const safe = Number.isFinite(value) ? Math.round(value) : 0;
  try {
    return new Intl.NumberFormat(locale === "en" ? "en-US" : "ar-IQ").format(safe);
  } catch {
    return String(safe);
  }
}

function safeUrl(value: string | null | undefined): string | null {
  if (!value) return null;
  try {
    const url = new URL(value);
    if (url.protocol !== "http:" && url.protocol !== "https:") return null;
    return url.toString();
  } catch {
    return null;
  }
}

function safeColor(value: string | null | undefined, fallback: string): string {
  if (!value) return fallback;
  return /^#[0-9A-Fa-f]{6}([0-9A-Fa-f]{2})?$/.test(value) ? value : fallback;
}

export function buildReceiptHtml(input: ReceiptInput): string {
  const dir = input.locale === "en" ? "ltr" : "rtl";
  const t = (ar: string, en: string) => (input.locale === "en" ? en : ar);

  const primary = safeColor(input.config?.primary_color, "#3B2C9C");
  const accent = safeColor(input.config?.accent_color, "#5B47C9");

  const logoUrl = safeUrl(input.schoolLogoUrl);
  const emblemUrl = safeUrl(input.config?.emblem_url);
  const bgPattern = safeUrl(input.config?.background_pattern_url);
  const decTL = safeUrl(input.config?.decoration_top_left);
  const decTR = safeUrl(input.config?.decoration_top_right);
  const decBL = safeUrl(input.config?.decoration_bottom_left);
  const decBR = safeUrl(input.config?.decoration_bottom_right);

  const thankYou = escapeHtml(input.config?.thank_you_text || t("شكراً لكم", "Thank you"));
  const footerNote = escapeHtml(
    input.config?.footer_note || t("تم إنشاء الإيصال من نظام إدارة المدرسة.", "Receipt generated by the school management system."),
  );

  const schoolName = escapeHtml(input.schoolName);
  const branchName = input.branchName ? escapeHtml(input.branchName) : "";
  const receiptNumber = escapeHtml(input.receiptNumber || "—");
  const studentName = escapeHtml(input.studentName || "—");
  const className = escapeHtml(input.className || "—");
  const paymentMethod = escapeHtml(input.paymentMethod || "—");
  const paymentDate = escapeHtml(input.paymentDate || "—");
  const notes = input.notes ? escapeHtml(input.notes) : "";

  const currency = t("د.ع", "IQD");
  const labelStudent = t("اسم الطالب", "Student name");
  const labelClass = t("الصف", "Class");
  const labelBranch = t("الفرع", "Branch");
  const labelMethod = t("طريقة الدفع", "Payment method");
  const labelDate = t("التاريخ", "Date");
  const labelReceiptNo = t("رقم الإيصال", "Receipt no.");
  const labelTotal = t("المبلغ الكلي", "Total fee");
  const labelDiscount = t("التخفيض", "Discount");
  const labelPaid = t("المبلغ المستلم", "Amount received");
  const labelRemaining = t("المبلغ المتبقي", "Remaining");
  const labelReceipt = t("إيصال", "Receipt");
  const labelNotes = t("ملاحظات", "Notes");

  const decoStyle = (url: string, pos: string) =>
    `<div class="r-deco r-deco-${pos}" style="background-image:url('${escapeHtml(url)}')"></div>`;

  const autoPrintScript =
    input.autoPrint === false
      ? ""
      : `<script>window.addEventListener('load',function(){setTimeout(function(){window.print();},150);},{once:true});</script>`;

  return `
    <html dir="${dir}">
      <head>
        <meta charset="utf-8" />
        <title>${labelReceipt}</title>
        <style>
          @font-face{
            font-family:"Noto Sans Arabic";
            src:url("/fonts/noto-sans-arabic/NotoSansArabic-Variable.ttf") format("truetype");
            font-display:swap;
          }
          @page{ size:A5 portrait; margin:0; }
          *{ box-sizing:border-box; }
          html,body{ margin:0; padding:0; }
          body{
            font-family:"Noto Sans Arabic",Segoe UI,Tahoma,Arial,sans-serif;
            color:#1a1a3e;
            background:#f5f3fb;
            -webkit-print-color-adjust:exact;
            print-color-adjust:exact;
          }
          .r-page{
            position:relative;
            width:148mm;
            min-height:210mm;
            margin:0 auto;
            padding:14mm 12mm;
            background:#ffffff
              ${bgPattern ? `url('${escapeHtml(bgPattern)}') center/cover no-repeat` : ""};
            overflow:hidden;
          }
          .r-frame{
            position:absolute;
            inset:6mm;
            border:2px solid ${primary};
            border-radius:6mm;
            pointer-events:none;
          }
          .r-frame::before, .r-frame::after{
            content:"";
            position:absolute;
            inset:1.2mm;
            border:1px solid ${accent};
            border-radius:5mm;
            opacity:.45;
          }
          .r-deco{
            position:absolute;
            width:28mm;
            height:28mm;
            background-size:contain;
            background-repeat:no-repeat;
            opacity:.7;
            z-index:0;
          }
          .r-deco-tl{ top:4mm; left:4mm; }
          .r-deco-tr{ top:4mm; right:4mm; }
          .r-deco-bl{ bottom:4mm; left:4mm; }
          .r-deco-br{ bottom:4mm; right:4mm; }
          .r-content{ position:relative; z-index:1; }
          .r-ribbon{
            position:absolute;
            top:0;
            ${dir === "rtl" ? "right" : "left"}:8mm;
            background:${primary};
            color:#fff;
            font-weight:700;
            font-size:14pt;
            padding:6mm 5mm 4mm;
            clip-path:polygon(0 0,100% 0,100% 100%,50% 90%,0 100%);
            min-width:22mm;
            text-align:center;
            z-index:2;
          }
          .r-head{
            text-align:center;
            margin-top:14mm;
            margin-bottom:5mm;
          }
          .r-logo{
            width:22mm; height:22mm;
            object-fit:contain;
            margin:0 auto 2mm;
            display:block;
          }
          .r-school{
            font-size:18pt;
            font-weight:800;
            color:${primary};
            margin:0 0 1mm;
          }
          .r-branch{
            font-size:11pt;
            color:${accent};
            font-weight:600;
            margin:0;
          }
          .r-receipt-no{
            text-align:${dir === "rtl" ? "left" : "right"};
            font-size:9pt;
            color:#5f7388;
            margin:2mm 0 4mm;
          }
          .r-receipt-no strong{ color:${primary}; font-family:monospace; }
          .r-divider{
            height:2px;
            background:linear-gradient(90deg,transparent,${accent},transparent);
            margin:3mm 0;
          }
          .r-grid{
            display:grid;
            grid-template-columns:1fr 1fr;
            gap:3mm 6mm;
            border:1px solid ${accent}33;
            border-radius:3mm;
            padding:4mm 5mm;
            background:#fafaff;
          }
          .r-field{ font-size:10pt; }
          .r-field-label{
            color:#6b6b8c;
            font-size:8pt;
            margin-bottom:1mm;
            font-weight:500;
          }
          .r-field-value{
            color:#1a1a3e;
            font-weight:700;
            font-size:11pt;
          }
          .r-amounts{
            margin-top:4mm;
            padding:4mm 5mm;
            border:1px solid ${accent}55;
            border-radius:3mm;
            background:linear-gradient(135deg,#fafaff,#f0edff);
          }
          .r-amounts-row{
            display:flex;
            justify-content:space-between;
            align-items:center;
            padding:1.5mm 0;
            border-bottom:1px dashed ${accent}33;
            font-size:10pt;
          }
          .r-amounts-row:last-child{ border-bottom:0; }
          .r-amounts-row .lbl{ color:#5f7388; font-weight:500; }
          .r-amounts-row .val{ font-weight:700; color:#1a1a3e; }
          .r-amounts-row.discount .val{ color:#D97706; }
          .r-amounts-row.remaining .val{ color:${Number(input.remaining) === 0 ? "#16A34A" : "#DC2626"}; }
          .r-paid{
            margin-top:5mm;
            padding:6mm 5mm;
            border:2px solid ${primary};
            border-radius:4mm;
            text-align:center;
            background:linear-gradient(135deg,#ffffff,#f0edff);
          }
          .r-paid-label{
            font-size:10pt;
            color:${accent};
            font-weight:600;
            margin-bottom:2mm;
          }
          .r-paid-amount{
            font-size:28pt;
            font-weight:900;
            color:${primary};
            letter-spacing:1px;
          }
          .r-notes{
            margin-top:4mm;
            padding:3mm 4mm;
            background:#fff8e1;
            border-${dir === "rtl" ? "right" : "left"}:3px solid #f59e0b;
            border-radius:2mm;
            font-size:9pt;
          }
          .r-notes-label{
            color:#92400e;
            font-weight:700;
            font-size:8pt;
            margin-bottom:1mm;
          }
          .r-emblem{
            width:14mm; height:14mm;
            object-fit:contain;
            display:block;
            margin:4mm auto 1mm;
            opacity:.85;
          }
          .r-thanks{
            text-align:center;
            font-size:14pt;
            font-weight:800;
            color:${primary};
            margin-top:3mm;
          }
          .r-footer{
            text-align:center;
            font-size:8pt;
            color:#7a7a9a;
            margin-top:3mm;
            padding-top:2mm;
            border-top:1px dashed ${accent}55;
          }
          @media print{
            body{ background:#fff; }
            .r-page{ box-shadow:none; }
          }
        </style>
      </head>
      <body>
        <div class="r-page">
          <div class="r-frame"></div>
          ${decTL ? decoStyle(decTL, "tl") : ""}
          ${decTR ? decoStyle(decTR, "tr") : ""}
          ${decBL ? decoStyle(decBL, "bl") : ""}
          ${decBR ? decoStyle(decBR, "br") : ""}
          <div class="r-ribbon">${labelReceipt}</div>
          <div class="r-content">
            <div class="r-head">
              ${logoUrl ? `<img class="r-logo" src="${escapeHtml(logoUrl)}" alt="${schoolName}" />` : ""}
              <h1 class="r-school">${schoolName}</h1>
              ${branchName ? `<p class="r-branch">${branchName}</p>` : ""}
            </div>
            <div class="r-receipt-no">
              ${labelReceiptNo}: <strong>${receiptNumber}</strong>
            </div>
            <div class="r-divider"></div>
            <div class="r-grid">
              <div class="r-field">
                <div class="r-field-label">${labelStudent}</div>
                <div class="r-field-value">${studentName}</div>
              </div>
              <div class="r-field">
                <div class="r-field-label">${labelClass}</div>
                <div class="r-field-value">${className}</div>
              </div>
              <div class="r-field">
                <div class="r-field-label">${labelDate}</div>
                <div class="r-field-value">${paymentDate}</div>
              </div>
              <div class="r-field">
                <div class="r-field-label">${labelMethod}</div>
                <div class="r-field-value">${paymentMethod}</div>
              </div>
            </div>
            <div class="r-amounts">
              <div class="r-amounts-row">
                <span class="lbl">${labelTotal}</span>
                <span class="val">${fmtMoney(input.totalFee, input.locale)} ${currency}</span>
              </div>
              <div class="r-amounts-row discount">
                <span class="lbl">${labelDiscount}</span>
                <span class="val">${fmtMoney(input.discount, input.locale)} ${currency}</span>
              </div>
              <div class="r-amounts-row remaining">
                <span class="lbl">${labelRemaining}</span>
                <span class="val">${fmtMoney(input.remaining, input.locale)} ${currency}</span>
              </div>
            </div>
            <div class="r-paid">
              <div class="r-paid-label">${labelPaid}</div>
              <div class="r-paid-amount">${currency} ${fmtMoney(input.paidNow, input.locale)}</div>
            </div>
            ${
              notes
                ? `<div class="r-notes"><div class="r-notes-label">${labelNotes}</div>${notes}</div>`
                : ""
            }
            ${emblemUrl ? `<img class="r-emblem" src="${escapeHtml(emblemUrl)}" alt="" />` : ""}
            <div class="r-thanks">${thankYou}</div>
            <div class="r-footer">${footerNote}</div>
          </div>
        </div>
        ${autoPrintScript}
      </body>
    </html>
  `;
}
